import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LoginButton from "../components/login-btn";
import Link from "next/link";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  // console.log(session);

  return (
    <div className={styles.container}>
      <h1 className="text-3xl font-bold underline text-center">Hello world!</h1>

      <LoginButton></LoginButton>
      <Head>
        <title>EventFour</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <br></br>
      <Link href="/wz/dashboard">Dashboard</Link>
      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
